export const Theme = {
  Sidebar: "#efefef",
  Section: "#bfaa81",
  Box: "#f2eee6",
  Blue: "#213446",
  Gold: "#bfaa81",
  GoldCommon: "#d5c8af",
  Black: "#464646",
  Gray: "#aaaaaa",
  Assistant: "'Assistant', serif",
  Playfair: "'Playfair Display', serif",
  widthNumber: document.body.clientWidth || window.innerWidth,
  pLeft: "25px",
  pRight: "35px",
  //media query
  largeBreakPoint:
    "@media only screen and (min-width: 1400px), only screen and (min-width: 500px) and (min-resolution: 2dppx)",
  mediumBreakPoint: "@media only screen and (max-width: 750px)",
  smallBreakPoint: "@media only screen and (max-width: 450px)",
  //sizes
  SidebarWidth: 67,
  SidebarWidth2x: 100,
  SidebarItems: 34,
  SidebarItemsSmall: 20,
  //Text
  videoTitleXs: "38px",
  videoTitle: "54px",
  videoTitle2x: "81px",
  textSize: "14px",
  textSize2x: "18px",
  textSmall: "11px",
  textSmall2x: "14.5px",
  textLogoSmall: "13px",
  textLogoSmall2x: "20px",
  textLogoBig: "25px",
  textLogoBig2x: "37.5px",
  textTitleGroup: "40px",
  textTitleGroup2x: "59.5px",
  textSubTitleGroup: "33px",
  textSubTitleGroup2x: "50.5px",
  textFooterTitleGroup: "12px",
  textFooterTitleGroup2x: "17.5px",
  TextBoxTitle: "30px",
  TextBoxTitle2x: "44.5px",
  TextSmallSubtitle: "14.5px",
  TextSmallSubtitle2x: "22px",

  //text menu
  MenuHeigth: "62px",
  MenuHeigth2x: "93px",
  MenuItemSmall: "12px",
  MenuItemSmall2x: "13px",
  MenuItemFull: "12.5px",
  MenuItemFull2x: "18.5px"
};
